[project]
name = "grok-trader"
version = "0.1.0"
description = "Dominate markets with data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.2.1",
    "tweepy>=4.16.0",
]
